### ISSUE TITLE
0.4.3 - no incoming call or SMS notifications on Android 4.4.4

### ISSUE THREAD

**Issue by mparol** [ossw/ossw-android#13]
Sony Xperia Z3 Compact, stock Android 4.4.4.
In 0.4.3 from Play Store I get no incoming call or SMS notifications.
In 0.4.1 release from GitHub I get incoming calls (without caller name), but no SMS notifications.
Other notifications (eg. email) are showing in both versions.

**Comment by mparol** [comment]
I have compiled latest version from repository today. It's late, can't check further, but I think it's logging:

`I/com.althink.android.ossw.notifications.parser.api19.NotificationParserApi19(11755): SKIP NON REMOVABLE NOTIFICATION`

every time when there's an incoming call.

This might also be of use (appears few lines earlier):
`D/InCall  (23583): StatusBarNotifier - Notifying IN_CALL_NOTIFICATION: Notification(pri=1 contentView=com.android.incallui/0x1090066 vibrate=null sound=null defaults=0x0 flags=0x2 kind=[null])`

**Comment by mparol** [comment]
There's also an exception being thrown before "SKIP NON REMOVABLE NOTIFICATION"

```
W/NotificationListenerService[NotificationListener](11755): Error running onNotificationPosted

W/NotificationListenerService[NotificationListener](11755): java.lang.NullPointerException

W/NotificationListenerService[NotificationListener](11755):     at com.althink.android.ossw.notifications.parser.BaseNotificationParser.hasActions(BaseNotificationParser.java:96)

W/NotificationListenerService[NotificationListener](11755):     at com.althink.android.ossw.notifications.parser.BaseNotificationParser.isValidAlert(BaseNotificationParser.java:82)

W/NotificationListenerService[NotificationListener](11755):     at com.althink.android.ossw.notifications.parser.api19.NotificationParserApi19.parse(NotificationParserApi19.java:63)

W/NotificationListenerService[NotificationListener](11755):     at com.althink.android.ossw.notifications.NotificationListener.parseNotification(NotificationListener.java:181)

W/NotificationListenerService[NotificationListener](11755):     at com.althink.android.ossw.notifications.NotificationListener.onNotificationPosted(NotificationListener.java:119)

W/NotificationListenerService[NotificationListener](11755):     at android.service.notification.NotificationListenerService$INotificationListenerWrapper.onNotificationPosted(NotificationListenerService.java:168)

W/NotificationListenerService[NotificationListener](11755):     at android.service.notification.INotificationListener$Stub.onTransact(INotificationListener.java:56)

W/NotificationListenerService[NotificationListener](11755):     at android.os.Binder.execTransact(Binder.java:404)

W/NotificationListenerService[NotificationListener](11755):     at dalvik.system.NativeStart.run(Native Method)
```

**Comment by vaspa** [comment]
Spent some time today to find a clean solution but it seems that on different phones we get slightly different notifications. On my phone Galaxy n7100 4.4.2 I've never got any incoming call notifications.
In the code of notification parser API19 none of remote view IDs matched BaseNotificationParser.COM_ANDROID_PHONE_LINE1/2 so I never get any alert.
Therefore, I've made a workaround. Hope it will not brake the incoming call notifications in other cases.

To test if it works please checkout my experimental branch **experimentUI**.
Feedback is welcome. There could be some errors on orientation change. The info how to reproduce them will be very useful.

[Latest firmware snapshot from Krzysztof](https://www.dropbox.com/s/1pgmqvhhml2nff2/ossw-firmware-s120-0.5.0-snapshot.zip?dl=0)

PS. There is a filter for notification applications in Settings, so you can choose which notifications can go to the watch.

**Comment by mparol** [comment]
Thanks. I have checked latest experimentUI branch, but no success. Notifications on SMS or incoming calls do not come through, only missed call notifications. But I have a fix. Will try to submit a pull request tomorrow.

**Comment by mparol** [comment]
Fixes are in pull request #19

**Comment by vaspa** [comment]
Do you still have any problems with incoming calls/SMS with the latest beta?

**Comment by mparol** [comment]
Calls and SMSs work OK in 0.5.0 with Mute and Decline options that you have posted on 20.12.2015 to the forum.
(still testing on the same Android 4.4.4 of course)
